version: 2.1
orbs:
  coveralls: coveralls/coveralls@1.0.4
jobs:
  build:
    docker:
      - image: circleci/node:lts
    working_directory: ~/repo
    steps:
      - checkout

      # - run: npm test -- --watch=false --code-coverage
      # - run: npm run e2e

      # specify version number to bypass permission error in CircleCi
      - setup_remote_docker:
          version: 19.03.12
      - run:
          name: Execute Pipeline (Build Source --> Test --> Build Web Server)
          command: |
            docker build -f integration.Dockerfile . -t lemon-mart:$CIRCLE_BRANCH
            mkdir -p docker-cache
            docker save lemon-mart:$CIRCLE_BRANCH | gzip > docker-cache/built-image.tar.gz
      - save_cache:
          key: build-image{{ .BuildNum}}
          paths:
            - docker-cache
      - store_artifacts:
          path: docker-cache/built-image.tar.gz
          destination: built-image.tar.gz

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
